# Generated by Django 3.2.6 on 2021-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='slug_title',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
