# Generated by Django 3.2.6 on 2021-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210824_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug_title',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
